### ISSUE TITLE
Коннектор с движком на стороне сервера

### ISSUE THREAD

**Issue by ivkalita** [ivkalita/web-game#23]
1. Реализовать API для перемещения игроком корабликов с планеты на планету. Коннектор должен пробрасывать это действие обработчику игры (движку). Описать это API в документации.
2. Реализовать метод - передача клиентам по веб-сокету информации о текущем игровом мире. Этот должен быть push метод, то есть, информация передается не в ответ на запрос клиента, а просто по некоторому тайм-ауту подключенным по веб-сокетам клиентам. Описать в API этот механизм.

**Comment by Davidyuk** [comment]
Как я понимаю, из этого таска не реализована только документация.
